import streamlit as st
import tempfile
import os

# -----------------------
# Import your modules
# -----------------------
from ocr.image_ocr import extract_text_from_image
from ocr.skill_extractor import extract_skills_from_text

from matching.semantic_matcher import semantic_similarity
from matching.skill_matcher import smart_skill_match
from matching.experience_matcher import experience_score
from matching.ats_scorer import compute_ats_score
from matching.fit_labeler import get_fit_label


# -----------------------
# Helper: Build ATS Report
# -----------------------
def build_report(resume_skills, job_skills, skill_pct, exp_score, sem_score, ats, label):
    report = f"""
SMART RESUME SCREENER — ATS REPORT
=================================

JOB SKILLS:
{job_skills}

---------------------------------
EXTRACTED RESUME SKILLS:
{resume_skills}

---------------------------------
SCORES
---------------------------------
Skill Match %      : {skill_pct}
Experience Score   : {exp_score}
Semantic Similarity: {sem_score}
Final ATS Score    : {ats}
Fit Label          : {label}

---------------------------------
Generated by Smart Resume Screener
"""
    return report


# -----------------------
# Page config
# -----------------------
st.set_page_config(
    page_title="Smart Resume Screener",
    page_icon="📄",
    layout="centered"
)

st.markdown("<h1 style='text-align:center;'>📄 Smart Resume Screener</h1>", unsafe_allow_html=True)
st.markdown("<h3 style='text-align:center;color:gray;'>Multimodal ATS — Image • Text</h3>", unsafe_allow_html=True)
st.markdown("<p style='text-align:center;'>Analyze resumes and get ATS insights instantly.</p>", unsafe_allow_html=True)
st.markdown("---")


# -----------------------
# Sidebar — Job details
# -----------------------
st.sidebar.header("🧾 Job Details")

job_skills = st.sidebar.text_input(
    "Required Skills (comma separated)",
    "python, machine learning, deep learning, tensorflow, data analysis, docker, git"
)

job_exp = st.sidebar.number_input(
    "Required Experience (years)",
    min_value=0,
    max_value=20,
    value=1
)

job_text = st.sidebar.text_area(
    "Job Description",
    "We are looking for a Machine Learning Engineer with strong skills in Python, ML, and Deep Learning."
)


# -----------------------
# Resume Input
# -----------------------
st.subheader("📥 Resume Input")

input_mode = st.radio(
    "Choose resume input method:",
    ["Upload Image (PNG/JPG)", "Paste Resume Text"],
    horizontal=True
)

resume_text = ""

# -------- Option 1: Upload image --------
if input_mode == "Upload Image (PNG/JPG)":
    uploaded_file = st.file_uploader(
        "Upload Resume Image",
        type=["png", "jpg", "jpeg"]
    )

    if uploaded_file:
        with tempfile.NamedTemporaryFile(delete=False) as tmp:
            tmp.write(uploaded_file.read())
            file_path = tmp.name

        st.success("✅ Image uploaded successfully!")
        resume_text = extract_text_from_image(file_path)

# -------- Option 2: Paste text --------
elif input_mode == "Paste Resume Text":
    resume_text = st.text_area(
        "Paste your resume text here:",
        height=250,
        placeholder="Paste your resume content here..."
    )


# -----------------------
# Safety check
# -----------------------
if not resume_text.strip():
    st.info("Please upload a resume image or paste resume text to continue.")
    st.stop()


# -----------------------
# Show resume text
# -----------------------
with st.expander("🔍 View Resume Text"):
    st.text(resume_text[:3000])


# -----------------------
# Skill extraction
# -----------------------
resume_skills = extract_skills_from_text(resume_text)

st.write("### 🛠 Extracted Skills")
st.write(resume_skills)


# -----------------------
# Experience input
# -----------------------
resume_exp = st.number_input(
    "Candidate Experience (years)",
    min_value=0,
    max_value=30,
    value=1
)


# -----------------------
# Evaluate button
# -----------------------
if st.button("🔎 Evaluate Resume"):
    # Skill matching
    skill_pct = smart_skill_match(resume_skills, job_skills)

    # Experience score
    exp_score = experience_score(resume_exp, job_exp)

    # Semantic similarity
    sem_score = semantic_similarity(resume_text, job_text)

    # Final ATS
    ats = compute_ats_score(skill_pct, exp_score, sem_score)

    # Fit label
    label = get_fit_label(ats)

    # -----------------------
    # Results
    # -----------------------
    st.markdown("## 📊 ATS Evaluation Results")

    col1, col2, col3 = st.columns(3)
    col1.metric("Skill Match %", f"{skill_pct}%")
    col2.metric("Experience Score", exp_score)
    col3.metric("Semantic Similarity", sem_score)

    st.markdown("---")
    st.subheader("🎯 Final Verdict")

    st.metric("Final ATS Score", ats)
    st.success(f"Fit Label: {label}")

    # -----------------------
    # Download Report
    # -----------------------
    report_text = build_report(
        resume_skills,
        job_skills,
        skill_pct,
        exp_score,
        sem_score,
        ats,
        label
    )

    st.download_button(
        label="📥 Download ATS Report",
        data=report_text,
        file_name="ATS_Report.txt",
        mime="text/plain"
    )
